---
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshot
metadata:
  name: new-groupsnapshot-demo
spec:
  source:
    volumeGroupSnapshotContentName: this-test
  volumeGroupSnapshotClassName: csi-hostpath-groupsnapclass
