---
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshot
metadata:
  name: new-groupsnapshot-demo
spec:
  source:
    selector:
      matchLabels:
        app.kubernetes.io/name: mysql
  volumeGroupSnapshotClassName: csi-hostpath-groupsnapclass
