---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: new-snapshotcontent-test
  annotations:
    test: toast
spec:
  deletionPolicy: Retain
  driver: hostpath.csi.k8s.io
  source:
    volumeHandle: this-handle
  volumeSnapshotRef:
    name: test-vs
    namespace: test-vs-ns
